version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: xlarge
  darwin:
    macos:
      xcode: "13.3.0"
    resource_class: xlarge

restore-workspace: &restore-workspace
  attach_workspace:
    at: ~/

restore-cache: &restore-cache
  restore_cache:
    keys:
      - cargo-v2-{{ checksum "rust-toolchain" }}-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}-{{ arch }}
      - repo-source-{{ .Branch }}-{{ .Revision }}

commands:
  set-env-path:
    steps:
      - run:
          name: Set the PATH env variable
          command: |
            # Also put the Rust LLVM tools into the PATH.
            echo 'export PATH="$HOME:~/.cargo/bin:~/.rustup/toolchains/$(cat rust-toolchain)-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:$PATH"' | tee --append $BASH_ENV
            source $BASH_ENV

jobs:
  cargo-fetch:
    executor: default
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - set-env-path
      - run: echo $HOME
      - run: cargo --version
      - run: rustc --version
      - run:
          name: Update submodules
          command: git submodule update --init --recursive
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-v2-{{ checksum "rust-toolchain" }}-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}-{{ arch }}
      - run: cargo update
      - run: cargo fetch
      - run: rustup install $(cat rust-toolchain)
      - run: rustup default $(cat rust-toolchain)
      - run: rustc --version
      - run: rm -rf .git
      - persist_to_workspace:
          root: ~/
          paths: .
      - save_cache:
          key: cargo-v2-{{ checksum "rust-toolchain" }}-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}-{{ arch }}
          paths:
            - "~/.cargo"
            - "~/.rustup"

  linux-build:
    executor: default
    steps:
    - set-env-path
    - *restore-workspace
    - *restore-cache
    - run:
        cargo --version
    - run:
        name: Linux Tests
        command: cargo test --verbose
        no_output_timeout: 30m

  naive-mac-build:
    executor: default
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo --version
      - run: rustc --version
      - run: rustup install $(cat rust-toolchain)
      - run: rustup target add aarch64-unknown-linux-gnu
      - run:
          name: MacOS Tests
          command: cargo test --verbose --target aarch64-unknown-linux-gnu
          no_output_timeout: 30m

  rustfmt:
    executor: default
    steps:
      - *restore-workspace
      - *restore-cache
      - set-env-path
      - run:
          name: Run cargo fmt
          command: cargo fmt --all -- --check
 
workflows:
  test-all:
    jobs:
      - cargo-fetch
      - linux-build:
          requires:
           - cargo-fetch
      - rustfmt:
          requires:
            - cargo-fetch
      # naive-mac-build
      # build



      
